# Its nana project for git hub action - https://www.youtube.com/watch?v=R8_veQiYBjI

# project github link from nana - https://github.com/nanuchi/my-project

-name : javaci with gradel 

  on :
    pull_request : 
      branches : [master]
    push_request :
      branches : [master]

  jobs:
    
    build:
      
      runs-on : ubuntu-latest

      steps:
  
      - name : checking out the code
        uses : actions/checkout@v2

      - name : setup up JDK 1.8 
        uses : actions/setup-jdk@v1
        with:
          java-versions: 1.8 

      - name: Grant execute permissions for gardel
        run: chmod +x gradelew

      - name : build with gradel 
        run : ./gradelew build

      - name : build with maven ( maven and gradel me jdk env hi setup krna hota hai)
        run : mvn clean install 

      - name : setup python env
        uses : action/setup-python@
          with:
            java-versions: 1.8 
        
      
      - name : build and push the docker image
        run : 
          docker login cred

      - name : build and push docker image to docker registry 
        uses : actions/build-docker-image@1.0
        with :
          image : docker file will be there in the root directory of the code itself. Ubuntu has preinstalled docker. 
          registry : my own docker hub repository where image need to be pushed. 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

    publish :

      needs: build 



    

